### PR TITLE
Add user settings and customizable page to load.

### PR DESCRIPTION
**Pull request by austinkregel**
This PR aims to do the following:
  - Add support for a configurable set of other sites.
     - This configurable set of sites is all configured via a JS file found in `$HOME/.APP_NAME/config.js` where `$HOME` is your home directory, and `.APP_NAME` is the name of this app from the package.json file
  - Add support for some user based settings
     - Add settings for frameless, framed, and no window control window variants.
     - Add setting for the app to remember which website was last selected and to load it when you reboot the app.
     - Add "always on top" or "floating" window mode which enables the app to float above almost all other apps so you can work on other things while watching, or surfing.

### CODE REVIEW

**Comment by austinkregel** [comment]
Presently this is broken when it is compiled for production... 😞

**Comment by oscartbeaumont** [comment]
Sorry, It's taken me so long to reply, I didn't get notified about this PR. There is no point testing on a Windows machine because they do not have support for `electron-widevinecdm` but I might look at support for widevine with Windows or just disabling Netflix on Windows. Also, have you tested all of the services you have added as some require special stuff (eg. Netflix requires widewine which is not in default Electron). Otherwise, everything is looking good.

**Comment by oscartbeaumont** [comment]
Please disable Devtools, and the "Show no windows controls" and "Show window titlebar" are causing crashes to Electron when being toggled, Other than that it is awesome, Thanks for your contribution.

**Comment by austinkregel** [comment]
🤔 I wonder if those two are mac specific options, they work as I expect for me without crashing... I'll disable devtools, and those options for non-mac systems 😄

**Comment by austinkregel** [comment]
I had to remove Hulu from the default config, because for their license of widevine they don't support older versions of Chrome. (The version of Chrome offered by electron v2.0.4 is Chrome 61... As of this comment we're on Chrome 72...)

**Comment by oscartbeaumont** [comment]
If you need you can bump the version of all the deps (including Electron). The newest version of Electron is 4.0.4 and has Chrome version 69.0.3497.106. That is with the assumption that `electron-widevinecdm` support the newer version of Electron because it is deprecated (If it doesn't I would consider trying to roll it myself since this would also hopefully allow for Windows support).

**Comment by oscartbeaumont** [comment]
Sorry, I have not merged this yet, life has been busy but hopefully, sometime over the next couple of days I will.

**Comment by austinkregel** [comment]
No worries. I know too well how life can impact programming stuffs. Do whatcha got to. I'm in no real rush 😄

**Pull request merged**
